### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by banksio** [Hyrules/WinLIFX#1]
Thanks for the invite @Hyrules! Do you want me to create a new website for this application, similar to WinHue?

**Comment by Hyrules** [comment]
Sure but I don’t have the page setup properly yet. I have screwed with the git and have lost some stuff I`ve done in the last hours so i’ll get back to you when i’m ready to create a page.

Thanks.


From: Nathan Banks
Sent: July 15, 2018 16:15
To: Hyrules/WinLIFX
Cc: Hyrules; Mention
Subject: [Hyrules/WinLIFX] Website (#1)

Thanks for the invite @Hyrules! Do you want me to create a new website for this application, similar to WinHue?

**Comment by Hyrules** [comment]
Ok the gh-pages branch is up and running you can create a website whenever you are ready.

**Comment by banksio** [comment]
@Hyrules Cheers, I'll clone the WinHue one for now with a few changes.

**Comment by banksio** [comment]
A simple website is up and running, closing for now.
