### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by banksio** [Hyrules/WinLIFX#2]
Got a few errors today trying to pull the latest master and build it. Is it me? Hope they aren't too hard to fix.

![image](https://user-images.githubusercontent.com/30214760/42900342-978f175a-8ac0-11e8-88e4-94b46266208b.png)

**Comment by Hyrules** [comment]
packages was missing you can try again I have made a new commit.

**Comment by banksio** [comment]
Thanks, that's most sorted. `System.Windows.Interactivity` still seems to be missing though?

![image](https://user-images.githubusercontent.com/30214760/42905446-fcb1e108-8acf-11e8-95f7-edf03115e50a.png)

**Comment by Hyrules** [comment]
ok you can try again I just found out it wasn't in the packages folder. Just pull the code again.

**Comment by banksio** [comment]
Perfect, it builds fine now
